Feature/rmio 89 switch to central package management
re-motion/IO pull request #22
Opened 2024-07-05 09:16 UTC by Frazerus

https://re-motion.atlassian.net/browse/RMIO-89

2024-07-05 10:07 UTC, a-ctor requested changes

2024-07-05 10:07 UTC, a-ctor commented on NuGet.config
> -    <add key="re-motion Infrastructure" value="https://nuget.re-motion.org/nuget/re-motion-infrastructure/" />
As discussed, we need those to restore the packages in the Build project. Projects with a `packages.config` file won't be affected by central package management but they will be affected if we change the packages sources here

2024-07-08 07:42 UTC, a-ctor approved these changes

2024-07-08 07:53 UTC, MichaelKetting approved these changes

2024-07-08 08:13 UTC, merged